### ISSUE TITLE
json_info not documented

### ISSUE THREAD

**Issue by RIAEvangelist** [Moonware/cordova-cameraserver#4]
what are the possible keys?

can I change targetWidth here? or desieredPreview size?

**Comment by w3t** [comment]
json_info is a free dictionary that just allows to share data from your app through the http server (as http://server:8100/smartcam.json) since I needed to be able to send extra information to my Ionic application.

It has no settings that impact the behavior of the camera manager which you need to implement directly in cameramanager.java

**Comment by RIAEvangelist** [comment]
Thanks
